  version: "3"
  services:
    kafka1:
      image: "bitnami/kafka:latest"
      container_name: kafka1
      ports:
        - 9092:9092
      environment:
        KAFKA_CFG_NODE_ID: 1
        KAFKA_BROKER_ID: 1
        KAFKA_ENABLE_KRAFT: 'yes'
        KAFKA_CFG_PROCESS_ROLES: 'broker,controller'
        KAFKA_CFG_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'

        KAFKA_CFG_LISTENERS: 'INTERNAL://kafka1:29092,CONTROLLER://kafka1:2181,EXTERNAL://0.0.0.0:9092'
        KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
        KAFKA_CFG_ADVERTISED_LISTENERS: 'INTERNAL://kafka1:29092,EXTERNAL://localhost:9092'
        KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
        KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: '1@kafka1:2181'

        ALLOW_PLAINTEXT_LISTENER: yes
        KAFKA_KRAFT_CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
        BITNAMI_DEBUG: 'yes'
      volumes:
        - kafka1_data:/bitnami/kafka

  volumes:
    kafka1_data: